CREATE TABLE IF NOT EXISTS ATM_DATA (
    X DOUBLE NOT NULL,
    Y DOUBLE NOT NULL,
    NAME VARCHAR(100),
    ADDRESS VARCHAR(255),
    ZIPCODE INT,
    WARD INT,
    ID INT,
    MAR_ID INT,
    XCOORD DOUBLE,
    YCOORD DOUBLE,
    GIS_ID VARCHAR(255),
    CREATOR VARCHAR(255),
    CREATED TIMESTAMP NULL DEFAULT NULL,
    EDITOR VARCHAR(255),
    EDITED TIMESTAMP NULL DEFAULT NULL,
    GLOBALID CHAR(100),
    OBJECTID INT PRIMARY KEY
);
